version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  build-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install Dependencies and Build Electron App for Windows
          command: |
            npm install
            npm run dist-win
            echo "BUILD_DIR=$PWD/dist" >> $BASH_ENV
            mkdir -p $HOME/project/builds
            cp -r dist $HOME/project/builds
            pwd
            ls

  deploy-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Print Current Working Directory
          command: |
            pwd
            ls
            echo "Deploying from: $BUILD_DIR"  # Verify the build directory path

      - aws-s3/copy:
          install-aws-cli: true
          aws-access-key-id: PARAM_AWS_CLI_ACCESS_KEY_ID
          aws-secret-access-key: PARAM_AWS_CLI_SECRET_ACCESS_KEY
          aws-region: PARAM_AWS_CLI_REGION
          from: $BUILD_DIR
          to: s3://bhavanish1/etime/desktop/
          when: on_success

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-windows:
          filters:
            branches:
              only: master
      - deploy-windows:
          requires:
            - build-windows
          filters:
            branches:
              only: master
