version: 2.1

jobs:
  build-deploy-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install Dependencies and Build Electron App for Windows
          command: |
            npm install
            npm run dist-win
            pwd
            ls
            cp -r /root/project/dist $HOME  # Copy the dist folder to the new working directory

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Deploy Windows Artifacts to S3
          command: |
            cd /home/circleci/project  # Change to the correct working directory
            aws s3 sync ./dist s3://bhavanish/etime/desktop/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy-windows:
          filters:
            branches:
              only: master
