version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-s3: circleci/aws-s3@3.1.1
  
jobs:
  build-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install Dependencies and Build Electron App for Windows
          command: |
            npm install
            npm run dist-win
            pwd
            ls
            cp -r /root/project/dist $HOME  # Copy the dist folder to the new working directory

  deploy-windows:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            pwd  # Print current working directory
            ls   # List contents of the directory
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            ls   # List contents again to verify the zip file
            unzip awscliv2.zip
            ls   # List contents after unzipping
            sudo ./aws/install

      - run:
          name: Deploy Windows Artifacts to S3
          command: |
            pwd
            ls
            cd /home/circleci/project  # Change to the correct working directory
            aws s3 sync project s3://bhavanish/etime/desktop/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-windows:
          filters:
            branches:
              only: master
      - deploy-windows:
          requires:
            - build-windows
          filters:
            branches:
              only: master
