version: 2.1

jobs:
  build:
    docker:
      - image: node:14 # Use your desired Node.js version here
    steps:
      - checkout
      - run:
          name: Install Wine
          command: |
            apt-get update
            apt-get install -y wine
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build and Deploy
          command: npm run publish

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
