version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  build-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install Dependencies and Build Electron App for Windows
          command: |
            npm install
            npm run dist-win
            pwd
            ls
            cd dist
            ls
      - aws-s3/sync:
          install-aws-cli: true
          aws-access-key-id: PARAM_AWS_CLI_ACCESS_KEY_ID
          aws-secret-access-key: PARAM_AWS_CLI_SECRET_ACCESS_KEY
          aws-region: PARAM_AWS_CLI_REGION
          from: /root/project/dist/.
          to: s3://bhavanish1/etime/desktop/
          when: on_success

  build-mac:
    macos:
      xcode: "14.1.0"
    steps:
      - checkout
      - run:
          name: Install Node.js and npm
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install 14 # Choose the Node.js version you need
            node --version
            npm --version
            npm install
            npm run dist-mac
            pwd
            ls

      

      - aws-s3/sync:
          install-aws-cli: true
          aws-access-key-id: PARAM_AWS_CLI_ACCESS_KEY_ID
          aws-secret-access-key: PARAM_AWS_CLI_SECRET_ACCESS_KEY
          aws-region: PARAM_AWS_CLI_REGION
          from: /Users/distiller/project/dist/.
          to: s3://bhavanish1/etime/desktop/
          when: on_success

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-windows:
          filters:
            branches:
              only: master
      - build-mac:
          requires:
            - build-windows
          filters:
            branches:
              only: master
