version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  build-deploy-windows:
    docker:
      - image: electronuserland/builder:wine
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install Dependencies and Build Electron App for Windows
          command: |
            npm install
            npm run dist-win
            pwd
            ls

      - persist_to_workspace:
          root: /root/project
          paths:
            - dist  # Persist the dist folder to be used in the deploy step

  deploy-windows:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - restore_workspace:
          name: Restore the dist folder from the build step
          keys:
            - dist

      - run:
          name: Print Current Working Directory
          command: |
            pwd
            ls

      - aws-s3/sync: 
          install-aws-cli: true
          aws-access-key-id: PARAM_AWS_CLI_ACCESS_KEY_ID
          aws-secret-access-key: PARAM_AWS_CLI_SECRET_ACCESS_KEY
          aws-region: PARAM_AWS_CLI_REGION
          from: /root/project/dist
          to: s3://bhavanish1/etime/desktop/
          when: on_success 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy-windows:
          filters:
            branches:
              only: master
      - deploy-windows:
          requires:
            - build-deploy-windows
          filters:
            branches:
              only: master
