version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build Electron Application for Windows
          command: npm run dist-win

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

deploy:
  docker:
    - image: circleci/python:3.7
  steps:
    - checkout
    - run:
        name: Install AWS CLI
        command: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
    - run:
        name: Deploy to S3
        command: |
          aws s3 cp dist s3://your-bucket-name/etime/desktop/ --recursive
