version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.6
  aws-s3: circleci/aws-s3@3.1.1

jobs:
  build-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Install Dependencies and Build Electron App for Windows
          command: |
            npm install
            npm run dist-win
            pwd
            ls
            cp -r /root/project/dist $HOME  # Copy the dist folder to the new working directory
            echo "DIST_COPIED=true" >> $BASH_ENV  # Set an environment variable to indicate dist was copied

  deploy-windows:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Print Current Working Directory
          command: |
            pwd
            ls

      - run:
          name: Check if dist was copied
          command: |
            if [ -n "$DIST_COPIED" ]; then
              echo "Dist was copied"
            else
              echo "Dist was not copied"
            fi

      - run:
          name: Deploy Windows Artifacts to S3
          command: |
            if [ -n "$DIST_COPIED" ]; then
              aws s3 sync ./dist s3://bhavanish1/etime/desktop/
            else
              echo "Skipping deployment because dist was not copied"
            fi
          when: on_success 

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-windows:
          filters:
            branches:
              only: master
      - deploy-windows:
          requires:
            - build-windows
          filters:
            branches:
              only: master
