jobs:
  build-windows:
    docker:
      - image: electronuserland/builder:wine
    steps:
      - checkout
      - run:
          name: Set Environment Variables
          command: |
            export BUILD_DIR=/home/circleci/project/builds
          environment:
            BUILD_DIR: /home/circleci/project/builds

      - run:
          name: Install Dependencies and Build Electron App for Windows
          command: |
            npm install
            npm run dist-win
            cp -r dist "$BUILD_DIR"
            pwd
            ls

  deploy-windows:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Set Environment Variables
          command: |
            export BUILD_DIR=/home/circleci/project/builds
          environment:
            BUILD_DIR: /home/circleci/project/builds

      - run:
          name: Install AWS CLI
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install

      - run:
          name: Print Current Working Directory
          command: |
            pwd
            ls

      - run:
          name: Debug - List Source Directory Contents
          command: |
            echo "Contents of PARAM_AWS_S3_FROM:"
            ls "$BUILD_DIR/dist"

      - aws-s3/sync: 
          install-aws-cli: true
          aws-access-key-id: PARAM_AWS_CLI_ACCESS_KEY_ID
          aws-secret-access-key: PARAM_AWS_CLI_SECRET_ACCESS_KEY
          aws-region: PARAM_AWS_CLI_REGION
          from: "$BUILD_DIR/dist"
          to: s3://bhavanish1/etime/desktop/
          when: on_success
